abbr -a dev 'cd ~/Development'
abbr -a xp 'cd ~/Development/dev-xp'
abbr -a startup 'cd "/mnt/c/Users/RayBenefield/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup"'
abbr -a yt 'cd ~/Development/youtube'
abbr -a core 'cd "/mnt/c/Users/RayBenefield/Dropbox/My PC (Ray-PC)/Documents/My Games/CORE/Saved/Maps"'
abbr -a x 'cd src/node_modules/'
