" All loaded vim bundles through dein
source $HOME/.vim/bundles.vim

" Essentials for any of my vim setups
source $HOME/.vim/essentials.vim

" Keep things clear of clutter and errors
source $HOME/.vim/quality.vim

" Simple changes to ease the use of Vim
source $HOME/.vim/convenience.vim
