" All loaded vim bundles/plugins
source $HOME/.vim/bundles.vim

" Essentials for any of my vim setups
source $HOME/.vim/essentials.vim

" Keep things clear of clutter and errors
source $HOME/.vim/quality.vim

" Minor tweaks that make Vim more seamless
source $HOME/.vim/convenience.vim
