set -U FZF_DISABLE_KEYBINDINGS 0
set -U FZF_LEGACY_KEYBINDINGS 0
set -U FZF_FIND_FILE_COMMAND "git ls"
set -U FZF_OPEN_COMMAND "git ls"
set -U FZF_CD_WITH_HIDDEN_COMMAND "git ls"
set -U FZF_CD_COMMAND "git ls"
