language: node_js
node_js:
    - '8'
branches:
    only:
        - master
cache: yarn
before_install: git fetch --depth=10000
install:
    - yarn
script:
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run test; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run lint; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run lint:commits; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run inspect; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run build; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run kd version; fi
before_deploy:
    - yarn run update
    - yarn run build --changed
deploy:
    provider: script
    script: yarn run publish
    skip_cleanup: true
    on:
        branch: master
env:
    global:
        - GH_USER=Raymond Benefield
        - GH_EMAIL=raymond.benefield@gmail.com
        - GH_REPO=RayBenefield/dev-xp
        - secure: 0WBB27gebHzTnaBpt2O60VZNg0rPtfAedIGnakRu9Vb+xMcowrjnaJfZxVShbkw6Tr7mgB7uKozOg7Sc1TBogp7LAtDLvqrfSuW8DThI3Gr+Cdf78oZLnOD+J1/R8SvBEuMAq44fHbRK6x3Mo9EVfdaCd0ZEcJZK6a3TEvE2UlW2zoh4xAbKk+Z1x4TRf1oHfmDJ+eLda6fi140YPDTN4ys7AfMS6Z4ns8wI24AkpznIwvTepXwCNzCx3YeaSeHYixUqF8zakdZAXBWs+a6sBKCPSSck/0iy5T/JQgWLp3F0HsjS9mNFo3Q1HKzJVX88tcL+fTuJZSFIoDA+rEql1v0jegTQ3yG6dKGksuJv4U22qGN3WaGXFr8imWW+D1wMwCRTr6l4R2RVdcMee/dMIsanv6cQ7iEJhp/6p/4kvtZU+dv+cDZtOdbNlAoQCEVyt2wDlW6iga14eMgSuDkePRuR7EeYX0yqvoFsDSxR1NO98m4VrA+yreJcA5tIdqlLgjKePBKKOx9sX+/WAdzyuvSQdcXnb0FFmT1mYS1JNp+F2n5O9SdlMevKk033t2rTyOQlaqclrEczo93YhvhUL2Y3Hma8SovSLpF8f85cbGna7Km6LjNvEXm9SbHg/jCq8lwJmkyAqgR1PDnbEB0VC88hXqA69XlO62an/3hTgA4=
        - secure: OYdHjCr6XTJ08rtqLW5gWsz/nZHfFBDFmTTJQ6BTCnNeNAjHbM6nPCeeoqelwGG2Sk4SahxRPLhPNN1K4rzL4m0647W7zQ4KP73XtzwFEgm7WaQawwa9VlIdSoksOFDb4sxWCumTcz4kua1QLkYKbl5uu92jFAdgXdfx3+GoXgHYSFh/D5IMXLQrCCb8SbL3FRgfI6pr0Xu/nAF/LDyVeQdaVvglhDg8FeEa4FhZiPLv34ZufnK85B4SD1HntJ36bj2J6g/jNSH/NBRFJrMTIM7c0pGyUK2UdEJ2mHo+C1Y1y+I+HnfOrSs8s6hsyGZQWrJtXjZzCdmaDu/A/puYMvS6mNCdFcdZPO+RspTMUM9IE5b1P8vFSC55kB7lE2BebLO9CYuA/wPnUXiyFvywySxy4cR2ed6GhsIYp1jfl5QCH1/LZ/uxzVIKQTl4FVBgZEhXQZQG8qD7ofKbvpcowbWxwPr7GvIFkT0D6CSeNzC2L5tlvdMR7FRWlZ8xVucFgnDDW/ZeQF4OICvUF/MNHBWwHk5tT7Wzwfmfs5g1Usts+I/R2MjMzPmXNLF1gwHqHSKRNAP9XU6ycwP09oVF8y3NGIHapKOsK2QkWSXKuYOvmltYbWcI9iAJ4neAboB34DWak8i6SIxezJA1WuPaV3VkZWjeEk8Ay7F4QEQQwkQ=
notifications:
    slack:
        rooms:
            - secure: fa4KA3puH30V6Y6Vhor/fUZQGgqmme5bDj/u3qxnKv7gUPXpDBQY1tf9MQ77OeOwFGTFZzgoxVMMBGfHpgkmWwDoeq0VVWBHfO90fnrQTb/mPCaQjKiRyKx16vquWmwpuwOL0chkLxtLp63tctJesPfgwRRKEY6y1QTXE4ato7JpVWneg8zY8D3eLFlua/UdYu/rOnWVWA8cp8OaDcDTPzJZl47dnivuIg4oYmuV/3V/hyWAqLwzbHok18858t0FiultbZJKVA8MLWyv/SW0TJ3pyLm8N+1sjKKovEYTZ/4JrYPQ6DwlZAoIj894gwmq8a7F3Nh2qTRo6XCfmR0RiNotaMrmiKXtvz9FKC2YEhVLeOjNqWPggC/lZEsBzGUlEjoMwg3m/fe+s+qoDqLN/XbY3u+h7Szb1VsRThdjqppmzVAyd7xZ1WNtLhmbs5jtHVPtO4djV2piO+jLmLnSf8/c2FB4t3O8AcTgavs5AzcgP/1qtN+WwCMdW1aezalsRLLtGWN8+Ap48tHcwbDveENqDPo9/Nwam8TDsNn13LpWbipOhZSsZLK6UP6JW/Mh+isY4cd7i/vJQCj0akouEMY40mmI4EnXkiauLnHEdannl6mehp4bUc50KjYIH+Y1xmFzmknMEfdBOq+N0RFdXP0UNm0QeKUU6ygGMC58kN8=
