language: node_js
node_js:
    - '11'
branches:
    only:
        - master
cache: yarn
before_install: git fetch --depth=10000
install:
    - yarn
script:
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run test; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run lint; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run lint:commits; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run inspect; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run build; fi
    - if ! [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then yarn run kd version; fi
before_deploy:
    - yarn run update
    - yarn run build --publishing
deploy:
    provider: script
    script: yarn run publish
    skip_cleanup: true
    on:
        branch: master
env:
    global:
        - GH_USER=Raymond Benefield
        - GH_EMAIL=raymond.benefield@gmail.com
        - GH_REPO=RayBenefield/dev-xp
        - secure: 0WBB27gebHzTnaBpt2O60VZNg0rPtfAedIGnakRu9Vb+xMcowrjnaJfZxVShbkw6Tr7mgB7uKozOg7Sc1TBogp7LAtDLvqrfSuW8DThI3Gr+Cdf78oZLnOD+J1/R8SvBEuMAq44fHbRK6x3Mo9EVfdaCd0ZEcJZK6a3TEvE2UlW2zoh4xAbKk+Z1x4TRf1oHfmDJ+eLda6fi140YPDTN4ys7AfMS6Z4ns8wI24AkpznIwvTepXwCNzCx3YeaSeHYixUqF8zakdZAXBWs+a6sBKCPSSck/0iy5T/JQgWLp3F0HsjS9mNFo3Q1HKzJVX88tcL+fTuJZSFIoDA+rEql1v0jegTQ3yG6dKGksuJv4U22qGN3WaGXFr8imWW+D1wMwCRTr6l4R2RVdcMee/dMIsanv6cQ7iEJhp/6p/4kvtZU+dv+cDZtOdbNlAoQCEVyt2wDlW6iga14eMgSuDkePRuR7EeYX0yqvoFsDSxR1NO98m4VrA+yreJcA5tIdqlLgjKePBKKOx9sX+/WAdzyuvSQdcXnb0FFmT1mYS1JNp+F2n5O9SdlMevKk033t2rTyOQlaqclrEczo93YhvhUL2Y3Hma8SovSLpF8f85cbGna7Km6LjNvEXm9SbHg/jCq8lwJmkyAqgR1PDnbEB0VC88hXqA69XlO62an/3hTgA4=
        - secure: oqNLA02DiZ2roraYvfSPk6jNbWRBSn6RQ9K0ro/NzEs/qWlzukdxq3rJUYdeZMJFi9+yTQyri/1Yn7OcujigKJQKh4GEfbMYk1b+SXNoIyghdrpK8rtJFL0BLPJYXsqQ7ESgRT5s/h/Psbace2neNdARSHjUo1sQtYfTQN//ZLSpr5GduHb7dL7MwxlSqI8MXWEDWicjig6P0MSh9NtI3D6VH2lsxfFMoHWbcHs4WkGYR3ziOY4rlpVhL1vwHqfdVk45wbQrcFZKylBRtd+efVcbdAwgvkMxOrvdu9Q4MlryQ3fLoy0BAo0lDHd05i4SN+6jV7nvauv/q2IgQw2jjuvyga6cAkOqM/TFnWwdiDgnET5hdGFOGU5dt0T5QYrdIkpdTGhuqlKKiLH+4E5hiHjGqwwHX28NQ2C3N23WXawtW2FVJNZ0n5DOvv7ob1x2WWKZebxCSTvadx4eYmZCWfRX2ywMJnmYdJAowqgt5iNQryeOy5HVRbj2mYnnCBIYC2NQAA1/n+TSuz99H+PSBrGF62WLUeFWd9dCDrAKut1cVBtbid1/3NfeBDil3YssVnxHKRU62C7/Vp/2ociTR09QsKtR1ZKVp+Per3BQZ6R1gtWS5YBc3b/ao3uLaDQlI+ahBYqf/QiJsY0Dyq1iYtQneXCDWRnbNHOfpdFPHw0=
notifications:
    slack:
        rooms:
            - secure: fa4KA3puH30V6Y6Vhor/fUZQGgqmme5bDj/u3qxnKv7gUPXpDBQY1tf9MQ77OeOwFGTFZzgoxVMMBGfHpgkmWwDoeq0VVWBHfO90fnrQTb/mPCaQjKiRyKx16vquWmwpuwOL0chkLxtLp63tctJesPfgwRRKEY6y1QTXE4ato7JpVWneg8zY8D3eLFlua/UdYu/rOnWVWA8cp8OaDcDTPzJZl47dnivuIg4oYmuV/3V/hyWAqLwzbHok18858t0FiultbZJKVA8MLWyv/SW0TJ3pyLm8N+1sjKKovEYTZ/4JrYPQ6DwlZAoIj894gwmq8a7F3Nh2qTRo6XCfmR0RiNotaMrmiKXtvz9FKC2YEhVLeOjNqWPggC/lZEsBzGUlEjoMwg3m/fe+s+qoDqLN/XbY3u+h7Szb1VsRThdjqppmzVAyd7xZ1WNtLhmbs5jtHVPtO4djV2piO+jLmLnSf8/c2FB4t3O8AcTgavs5AzcgP/1qtN+WwCMdW1aezalsRLLtGWN8+Ap48tHcwbDveENqDPo9/Nwam8TDsNn13LpWbipOhZSsZLK6UP6JW/Mh+isY4cd7i/vJQCj0akouEMY40mmI4EnXkiauLnHEdannl6mehp4bUc50KjYIH+Y1xmFzmknMEfdBOq+N0RFdXP0UNm0QeKUU6ygGMC58kN8=
            - secure: MPHK1LHv79KaiXV+geclJ5bxztifpP06F7bsdChcmvS0GvlDpBbC6E51yZhVARtvzK1iWsUtq2vSFILjqD44qtlIzhEOY54lvh61XsSlRV8X9eR2lT++yv35JVDmdImGpVlvRMf4NR9PBW7bp0lYCE66W6TE0NyyF6lNzojZMUKDx7oHbggzjS/oEVWTiUcHjQTX8bMGVTguBHeuKFjGDx81oBQYksLygc/StUK28w3x6AG3NRD3YlJhciqjO3OFGPGYSSV41OKwA2usmZ0Rayrhi+pUMg9qFqazi5zFaob2889j6+uyXc7BJ4BVcoinK1vVHTVpzEC5K4k3WVdbwjz98VmlP2ObVWtLFuI+b6BpHKv1/qWu8XIUqqgkXaQxMO8qA1raw3eJaiuA3ZCVn9SzAZhHExdXR+YvO5rzff4qKz0ihcHzpWAsa/qv96f03HLCd43CNYr4oyxdQ2lOCam8W0wjDaqXa52Tje3KiHXEV5fQb6LIt7ITOgVcdKc3mDzqLCyttlkX2mCFNpEJGoygIO/qxwi/w7kSGP5H2hEcAcYK+C6VX0Mld2kr970xCeFGoTRfvqxfv92LcXoHugWT2uLKts1XuyitmkwDTPfSjLUoCoWBqpwnd9ET8JWtbVGtbtEF264Lfpy3CAqxVm77JgfPtYUp6hW2/r1BQz4=
