taskkill /f /im FortniteClient-Win64-Shipping_BE.exe
taskkill /f /im FortniteClient-Win64-Shipping.exe
taskkill /f /im FortniteClient-Win64-Test.exe
taskkill /f /im FortniteClient-Win64-Shipping_EAC.exe
taskkill /f /im FortniteLauncher.exe
taskkill /f /im UnrealEditorFortnite.exe
taskkill /f /im UnrealEditorFortnite-Win64-Shipping.exe
taskkill /f /im CrashReportClientEditor.exe
taskkill /f /im URC.exe