#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#SingleInstance force
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#Include %A_ScriptDir%/lib/emoji-macro.ahk

#Hotstring x

::<3::pasteEmoji("💖")
::dead::pasteEmoji("💀")
::eyes::pasteEmoji("👀")
::!::pasteEmoji("⚠️")
::rt::pasteEmoji("♻️")
::time::pasteEmoji("⌛")
::light::pasteEmoji("💡")
::camera::pasteEmoji("📷")
::film::pasteEmoji("📽️")
::video::pasteEmoji("📽️")
::mic::pasteEmoji("🎤")
::pc::pasteEmoji("🖥️")
::star::pasteEmoji("🌟")
::music:: pasteEmoji("🎼")
::facepalm::pasteEmoji("🤦")
::wizard::pasteEmoji("🧙")
::speaker::pasteEmoji("🔊")
::?::pasteEmoji("❓")
::paint::pasteEmoji("🎨")
::brain::pasteEmoji("🧠")
::note::pasteEmoji("📝")
::check::pasteEmoji("✔️")
::users::pasteEmoji("👥")
::talk::pasteEmoji("🗣️")
::speak::pasteEmoji("🗣️")
::>::pasteEmoji("►")
::fire::pasteEmoji("🔥")
::hot::pasteEmoji("🥵")
::game::pasteEmoji("🎮")
::info::pasteEmoji("ℹ️")
::key::pasteEmoji("🔑")
::gem::pasteEmoji("💎")
::tools::pasteEmoji("🛠️")
::create::pasteEmoji("🛠️")
::creative::pasteEmoji("🛠️")
::food::pasteEmoji("🍜")
::idea::pasteEmoji("💡")
::light::pasteEmoji("💡")
::bulb::pasteEmoji("💡")
::cal::pasteEmoji("📅")
::cheers::pasteEmoji("🥂")

::excited::pasteEmoji("🤩")
::wink::pasteEmoji("😉")
::;)::pasteEmoji("😉")
::sob::pasteEmoji("😭")
::please::pasteEmoji("🥺")
::lol::pasteEmoji("🤣")
::drool::pasteEmoji("🤤")
::`:D::pasteEmoji("😁")
::smirk::pasteEmoji("😏")
::think::pasteEmoji("🤔")
::`:P::pasteEmoji("😋")
::<3eyes::pasteEmoji("😍")
::shy::pasteEmoji("😅")
::nervous::pasteEmoji("😅")
::confuse::pasteEmoji("😕")
::unamused::pasteEmoji("😒")
::rude::pasteEmoji("😒")
::cool::pasteEmoji("😎")
::shh::pasteEmoji("🤫")
::evil::pasteEmoji("😈")
::blown::pasteEmoji("🤯")
::yikes::pasteEmoji("😬")

::ok::pasteEmoji("👌")
::yep::pasteEmoji("👍")
::nope::pasteEmoji("👎")
::o/::pasteEmoji("👋")
::hi::pasteEmoji("👋")
::write::pasteEmoji("✍️")
::cross::pasteEmoji("🤞")
::up::pasteEmoji("☝️")
::pray::pasteEmoji("🙏")
::down::pasteEmoji("👇")
::arm::pasteEmoji("💪")
::strong::pasteEmoji("💪")
::flex::pasteEmoji("💪")

::flip::pasteEmoji("(╯'□')╯︵ ┻━┻", 1)
::shrug::pasteEmoji("¯\_(シ)_/¯", 1)
::fist::pasteEmoji("🤜🤛", 1)
