#!/bin/bash
git stash -u
BRANCH=$(git symbolic-ref --short HEAD)
git checkout master
git fetch --all --tags --prune
git pull --rebase --tags
vim ./docs/healthlog.md
APPLE=$(<./dx/.apple)
((++APPLE))
echo ${APPLE} > ./dx/.apple
git commit -am "docs(healthlog): Log stride towards healthy living ${APPLE}." -m "[skip ci]" --no-verify
git push --no-verify
git checkout ${BRANCH}
git rebase master
git stash pop
